import { type UserRoleType } from '@memoriaali/api-types';

/**
 * Single source of truth for permissions and role → permissions mapping.
 * Use colon notation: resource:action[:scope]
 */
export const ALL_PERMISSIONS = [
  'admin:all',
  'admin:manage',
  'comments:create',
  'comments:delete',
  'comments:moderate',
  'comments:read',
  'comments:update',
  'comments:write',
  'documents:approve',
  'documents:create',
  'documents:delete',
  'documents:publish',
  'documents:read',
  'documents:update',
  'documents:write',
  'groups:create',
  'groups:delete',
  'groups:manage',
  'groups:read',
  'groups:update',
  'metadatasuggestions:create',
  'metadatasuggestions:delete',
  'metadatasuggestions:moderate',
  'metadatasuggestions:read',
  'metadatasuggestions:update',
  'oralhistories:create',
  'oralhistories:delete',
  'oralhistories:read',
  'oralhistories:update',
  'research:approve',
  'research:read',
  'research:request',
  'uploads:create',
  'uploads:read',
  'users:create',
  'users:delete',
  'users:manage',
  'users:read',
  'users:update',
  'users:write',
  'sip:read',
  'sip:write',
] as const;

export type Permission = (typeof ALL_PERMISSIONS)[number];

/**
 * Permissions by role.
 */
export const ROLE_PERMISSIONS: Record<UserRoleType, Permission[]> = {
  USER: [
    'documents:read',
    'documents:create',
    'documents:delete',
    'comments:create',
    'comments:delete',
    'comments:read',
    'comments:update',
    'users:read',
    'groups:read',
    'research:read',
    'research:request',
    'metadatasuggestions:create',
    'metadatasuggestions:read',
    'oralhistories:read',
    'oralhistories:create',
    'uploads:create',
    'uploads:read',
  ],
  EXPERT: [
    'documents:read',
    'documents:create',
    'documents:write',
    'documents:update',
    'documents:delete',
    'comments:create',
    'comments:delete',
    'comments:moderate',
    'comments:read',
    'comments:update',
    'comments:write',
    'oralhistories:read',
    'oralhistories:create',
    'oralhistories:update',
    'research:read',
    'research:request',
    'metadatasuggestions:create',
    'metadatasuggestions:read',
    'metadatasuggestions:update',
    'metadatasuggestions:moderate',
    'uploads:create',
    'uploads:read',
  ],
  MODERATOR: [
    'documents:read',
    'documents:create',
    'documents:write',
    'documents:update',
    'documents:approve',
    'documents:delete',
    'comments:create',
    'comments:delete',
    'comments:moderate',
    'comments:read',
    'comments:update',
    'comments:write',
    'oralhistories:read',
    'oralhistories:create',
    'oralhistories:update',
    'oralhistories:delete',
    'research:read',
    'research:request',
    'research:approve',
    'users:read',
    'groups:create',
    'groups:read',
    'groups:delete',
    'groups:manage',
    'groups:update',
    'metadatasuggestions:create',
    'metadatasuggestions:read',
    'metadatasuggestions:update',
    'metadatasuggestions:moderate',
    'uploads:create',
    'uploads:read',
  ],
  ADMIN: [
    'users:read',
    'users:create',
    'users:write',
    'users:update',
    'users:delete',
    'users:manage',
    'comments:create',
    'comments:delete',
    'comments:moderate',
    'comments:read',
    'comments:update',
    'comments:write',
    'groups:read',
    'groups:create',
    'groups:update',
    'groups:delete',
    'groups:manage',
    'documents:read',
    'documents:create',
    'documents:write',
    'documents:update',
    'documents:delete',
    'documents:approve',
    'documents:publish',
    'oralhistories:read',
    'oralhistories:create',
    'oralhistories:update',
    'oralhistories:delete',
    'research:read',
    'research:request',
    'research:approve',
    'metadatasuggestions:create',
    'metadatasuggestions:read',
    'metadatasuggestions:update',
    'metadatasuggestions:delete',
    'metadatasuggestions:moderate',
    'uploads:create',
    'uploads:read',
    'admin:manage',
    'admin:all',
    'sip:read',
    'sip:write',
  ],
};

// Alias for backward compatibility
export const rolePermissions = ROLE_PERMISSIONS;
