/* eslint-disable no-undef */
/**
 * Comprehensive unit tests for generate-field-picking-helpers.js
 *
 * Test Contract:
 * - Tests validate real behavior of field picking helper generation
 * - Uses actual field metadata structures and validates generated TypeScript output
 * - Tests safe field picking, admin selectors, and helper functions
 * - Validates error conditions and edge cases
 * - Achieves comprehensive code coverage through real behavior testing
 */

import fs from 'fs';
import path from 'path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { generateFieldPickingHelpers } from '../generate-field-picking-helpers.js';

describe('generate-field-picking-helpers.js', () => {
  let tempDir;
  let outputFile;

  beforeEach(() => {
    // Create temporary directory for test outputs
    tempDir = path.join(process.cwd(), 'temp-field-helpers-output');
    if (!fs.existsSync(tempDir)) {
      fs.mkdirSync(tempDir, { recursive: true });
    }
    outputFile = path.join(tempDir, 'field-selectors.ts');
  });

  afterEach(() => {
    // Clean up test files
    if (fs.existsSync(outputFile)) {
      fs.unlinkSync(outputFile);
    }
    if (fs.existsSync(tempDir)) {
      fs.rmdirSync(tempDir, { recursive: true });
    }
  });

  describe('generateFieldPickingHelpers', () => {
    describe('Contract: Generate field picking helpers for models', () => {
      it('should generate complete helpers for single model with mixed fields', async () => {
        const sensitiveFieldsMap = {
          User: {
            allFields: ['id', 'username', 'email', 'hashedPassword', 'role'],
            sensitiveFields: [{ name: 'email' }, { name: 'hashedPassword' }],
            fieldsWithAnnotations: [
              { name: 'email', securityLevel: 'sensitive' },
              { name: 'hashedPassword', securityLevel: 'never-expose' },
            ],
            fieldsBySecurityLevel: {
              public: ['id', 'username', 'role'],
              sensitive: ['email'],
              adminOnly: [],
              neverExpose: ['hashedPassword'],
            },
          },
        };

        await generateFieldPickingHelpers(tempDir, sensitiveFieldsMap);

        expect(fs.existsSync(outputFile)).toBe(true);
        const generatedContent = fs.readFileSync(outputFile, 'utf-8');

        // Test header (including eslint directive)
        expect(generatedContent).toContain('// Generated by');
        expect(generatedContent).toContain('// DO NOT EDIT - This file is automatically generated');

        // Test User field picking helpers
        expect(generatedContent).toContain('// User field picking helpers');

        // Test safe fields array (excluding sensitive fields)
        expect(generatedContent).toContain('export const userSafeFields = [');
        expect(generatedContent).toContain("'id',");
        expect(generatedContent).toContain("'username',");
        expect(generatedContent).toContain("'role'");

        // Test that safe fields exclude sensitive ones
        const safeFieldsMatch = generatedContent.match(/userSafeFields = \[([\s\S]*?)\] as const;/);
        expect(safeFieldsMatch).toBeTruthy();
        expect(safeFieldsMatch[1]).not.toContain('email');
        expect(safeFieldsMatch[1]).not.toContain('hashedPassword');
        expect(generatedContent).toContain('] as const;');

        // Test safe fields type
        expect(generatedContent).toContain(
          'export type UserSafeFields = typeof userSafeFields[number];',
        );

        // Test all fields array
        expect(generatedContent).toContain('export const userAllFields = [');
        expect(generatedContent).toContain("'id',");
        expect(generatedContent).toContain("'username',");
        expect(generatedContent).toContain("'email',");
        expect(generatedContent).toContain("'hashedPassword',");
        expect(generatedContent).toContain("'role'");

        // Test public selector function
        expect(generatedContent).toContain('export function createUserPublicSelector() {');
        expect(generatedContent).toContain('return {');
        expect(generatedContent).toContain('id: true,');
        expect(generatedContent).toContain('username: true,');
        expect(generatedContent).toContain('role: true');

        // Test that public selector excludes sensitive fields
        const publicSelectorMatch = generatedContent.match(
          /export function createUserPublicSelector\(\) \{[\s\S]*?return \{([\s\S]*?)\};[\s\S]*?\}/,
        );
        expect(publicSelectorMatch).toBeTruthy();
        expect(publicSelectorMatch[1]).not.toContain('email: true');
        expect(publicSelectorMatch[1]).not.toContain('hashedPassword: true');

        // Test admin selector function (excludes never-expose fields)
        expect(generatedContent).toContain('export function createUserAdminSelector() {');
        expect(generatedContent).toContain('return {');
        expect(generatedContent).toContain('id: true,');
        expect(generatedContent).toContain('username: true,');
        expect(generatedContent).toContain('email: true,');
        expect(generatedContent).toContain('role: true');

        // Test that admin selector excludes never-expose fields
        const adminSelectorMatch = generatedContent.match(
          /export function createUserAdminSelector\(\) \{[\s\S]*?return \{([\s\S]*?)\};[\s\S]*?\}/,
        );
        expect(adminSelectorMatch).toBeTruthy();
        // CRITICAL: hashedPassword is @never-expose, NOT included even for admin
        expect(adminSelectorMatch[1]).not.toContain('hashedPassword: true');
      });

      it('should handle model with no sensitive fields', async () => {
        const sensitiveFieldsMap = {
          PublicModel: {
            allFields: ['id', 'title', 'description', 'createdAt'],
            sensitiveFields: [],
            fieldsWithAnnotations: [],
            fieldsBySecurityLevel: {
              public: ['id', 'title', 'description', 'createdAt'],
              sensitive: [],
              adminOnly: [],
              neverExpose: [],
            },
          },
        };

        await generateFieldPickingHelpers(tempDir, sensitiveFieldsMap);

        const generatedContent = fs.readFileSync(outputFile, 'utf-8');

        // Test that all fields are considered safe
        expect(generatedContent).toContain('export const publicmodelSafeFields = [');
        expect(generatedContent).toContain("'id',");
        expect(generatedContent).toContain("'title',");
        expect(generatedContent).toContain("'description',");
        expect(generatedContent).toContain("'createdAt'");

        // Test that public and admin selectors are identical
        expect(generatedContent).toContain('export function createPublicModelPublicSelector() {');
        expect(generatedContent).toContain('export function createPublicModelAdminSelector() {');

        // Both should contain all fields
        const publicSelectorMatch = generatedContent.match(
          /createPublicModelPublicSelector\(\) \{[^}]+\}/,
        );
        const adminSelectorMatch = generatedContent.match(
          /createPublicModelAdminSelector\(\) \{[^}]+\}/,
        );

        expect(publicSelectorMatch).toBeTruthy();
        expect(adminSelectorMatch).toBeTruthy();

        // Both should include all fields
        expect(publicSelectorMatch[0]).toContain('id: true');
        expect(publicSelectorMatch[0]).toContain('title: true');
        expect(adminSelectorMatch[0]).toContain('id: true');
        expect(adminSelectorMatch[0]).toContain('title: true');
      });

      it('should handle model with all sensitive fields', async () => {
        const sensitiveFieldsMap = {
          SensitiveModel: {
            allFields: ['privateData', 'secretKey', 'hiddenInfo'],
            sensitiveFields: [
              { name: 'privateData' },
              { name: 'secretKey' },
              { name: 'hiddenInfo' },
            ],
            fieldsWithAnnotations: [
              { name: 'privateData', securityLevel: 'sensitive' },
              { name: 'secretKey', securityLevel: 'sensitive' },
              { name: 'hiddenInfo', securityLevel: 'sensitive' },
            ],
            fieldsBySecurityLevel: {
              public: [],
              sensitive: ['privateData', 'secretKey', 'hiddenInfo'],
              adminOnly: [],
              neverExpose: [],
            },
          },
        };

        await generateFieldPickingHelpers(tempDir, sensitiveFieldsMap);

        const generatedContent = fs.readFileSync(outputFile, 'utf-8');

        // Test that safe fields array is empty
        expect(generatedContent).toContain('export const sensitivemodelSafeFields = [');
        expect(generatedContent).toContain('] as const;');

        // Check that no fields are listed in safe fields (should be empty array)
        const safeFieldsMatch = generatedContent.match(/sensitivemodelSafeFields = \[([\s\S]*?)\]/);
        expect(safeFieldsMatch).toBeTruthy();
        const safeFieldsContent = safeFieldsMatch[1].trim();
        expect(safeFieldsContent).toBe('');

        // Test that public selector is empty (all fields are sensitive)
        expect(generatedContent).toContain(
          'export function createSensitiveModelPublicSelector() {',
        );
        const publicSelectorMatch = generatedContent.match(
          /createSensitiveModelPublicSelector\(\) \{[^}]+\}/,
        );
        expect(publicSelectorMatch).toBeTruthy();
        // Should contain empty return object
        expect(publicSelectorMatch[0]).toContain('return {');

        // Test owner selector has sensitive fields
        expect(generatedContent).toContain('export function createSensitiveModelOwnerSelector() {');
        const ownerSelectorMatch = generatedContent.match(
          /createSensitiveModelOwnerSelector\(\) \{[^}]+\}/,
        );
        expect(ownerSelectorMatch).toBeTruthy();
        expect(ownerSelectorMatch[0]).toContain('privateData: true');
        expect(ownerSelectorMatch[0]).toContain('secretKey: true');
        expect(ownerSelectorMatch[0]).toContain('hiddenInfo: true');

        // Test that admin selector has all sensitive fields
        expect(generatedContent).toContain('export function createSensitiveModelAdminSelector() {');
        const adminSelectorMatch = generatedContent.match(
          /createSensitiveModelAdminSelector\(\) \{[^}]+\}/,
        );
        expect(adminSelectorMatch).toBeTruthy();
        expect(adminSelectorMatch[0]).toContain('privateData: true');
        expect(adminSelectorMatch[0]).toContain('secretKey: true');
        expect(adminSelectorMatch[0]).toContain('hiddenInfo: true');
      });

      it('should generate helpers for multiple models', async () => {
        const sensitiveFieldsMap = {
          User: {
            allFields: ['id', 'email', 'password'],
            sensitiveFields: [{ name: 'email' }, { name: 'password' }],
            fieldsWithAnnotations: [
              { name: 'email', securityLevel: 'sensitive' },
              { name: 'password', securityLevel: 'never-expose' },
            ],
            fieldsBySecurityLevel: {
              public: ['id'],
              sensitive: ['email'],
              adminOnly: [],
              neverExpose: ['password'],
            },
          },
          Document: {
            allFields: ['id', 'title', 'content', 'authorId'],
            sensitiveFields: [{ name: 'content' }],
            fieldsWithAnnotations: [{ name: 'content', securityLevel: 'sensitive' }],
            fieldsBySecurityLevel: {
              public: ['id', 'title', 'authorId'],
              sensitive: ['content'],
              adminOnly: [],
              neverExpose: [],
            },
          },
          PublicInfo: {
            allFields: ['id', 'name', 'description'],
            sensitiveFields: [],
            fieldsWithAnnotations: [],
            fieldsBySecurityLevel: {
              public: ['id', 'name', 'description'],
              sensitive: [],
              adminOnly: [],
              neverExpose: [],
            },
          },
        };

        await generateFieldPickingHelpers(tempDir, sensitiveFieldsMap);

        const generatedContent = fs.readFileSync(outputFile, 'utf-8');

        // Test User helpers
        expect(generatedContent).toContain('// User field picking helpers');
        expect(generatedContent).toContain('export const userSafeFields = [');
        expect(generatedContent).toContain("'id'");
        expect(generatedContent).toContain('export function createUserPublicSelector() {');
        expect(generatedContent).toContain('export function createUserAdminSelector() {');

        // Test Document helpers
        expect(generatedContent).toContain('// Document field picking helpers');
        expect(generatedContent).toContain('export const documentSafeFields = [');
        expect(generatedContent).toContain("'id',");
        expect(generatedContent).toContain("'title',");
        expect(generatedContent).toContain("'authorId'");

        // Test that 'content' is excluded from safe fields but present in all fields
        const docSafeFieldsMatch = generatedContent.match(
          /documentSafeFields = \[([\s\S]*?)\] as const;/,
        );
        expect(docSafeFieldsMatch).toBeTruthy();
        expect(docSafeFieldsMatch[1]).not.toContain('content');
        expect(generatedContent).toContain('export function createDocumentPublicSelector() {');
        expect(generatedContent).toContain('export function createDocumentAdminSelector() {');

        // Test PublicInfo helpers
        expect(generatedContent).toContain('// PublicInfo field picking helpers');
        expect(generatedContent).toContain('export const publicinfoSafeFields = [');
        expect(generatedContent).toContain("'id',");
        expect(generatedContent).toContain("'name',");
        expect(generatedContent).toContain("'description'");
        expect(generatedContent).toContain('export function createPublicInfoPublicSelector() {');
        expect(generatedContent).toContain('export function createPublicInfoAdminSelector() {');
      });

      it('should generate master safe and admin field selector exports', async () => {
        const sensitiveFieldsMap = {
          User: {
            allFields: ['id', 'username', 'email'],
            sensitiveFields: [{ name: 'email' }],
            fieldsWithAnnotations: [{ name: 'email', securityLevel: 'sensitive' }],
            fieldsBySecurityLevel: {
              public: ['id', 'username'],
              sensitive: ['email'],
              adminOnly: [],
              neverExpose: [],
            },
          },
          Document: {
            allFields: ['id', 'title', 'content'],
            sensitiveFields: [{ name: 'content' }],
            fieldsWithAnnotations: [{ name: 'content', securityLevel: 'sensitive' }],
            fieldsBySecurityLevel: {
              public: ['id', 'title'],
              sensitive: ['content'],
              adminOnly: [],
              neverExpose: [],
            },
          },
        };

        await generateFieldPickingHelpers(tempDir, sensitiveFieldsMap);

        const generatedContent = fs.readFileSync(outputFile, 'utf-8');

        // Test master safe field selectors export
        expect(generatedContent).toContain('export const safeFieldSelectors = {');
        expect(generatedContent).toContain('user: createUserPublicSelector(),');
        expect(generatedContent).toContain('document: createDocumentPublicSelector(),');

        // Test owner field selectors export
        expect(generatedContent).toContain('export const ownerFieldSelectors = {');
        expect(generatedContent).toContain('user: createUserOwnerSelector(),');
        expect(generatedContent).toContain('document: createDocumentOwnerSelector(),');

        // Test master admin field selectors export
        expect(generatedContent).toContain('export const adminFieldSelectors = {');
        expect(generatedContent).toContain('user: createUserAdminSelector(),');
        expect(generatedContent).toContain('document: createDocumentAdminSelector(),');
      });

      it('should handle field names with special characters', async () => {
        const sensitiveFieldsMap = {
          SpecialModel: {
            allFields: ['id', 'field_with_underscores', 'field-with-dashes', 'fieldWithCamelCase'],
            sensitiveFields: [{ name: 'field_with_underscores' }],
            fieldsWithAnnotations: [{ name: 'field_with_underscores', securityLevel: 'sensitive' }],
            fieldsBySecurityLevel: {
              public: ['id', 'field-with-dashes', 'fieldWithCamelCase'],
              sensitive: ['field_with_underscores'],
              adminOnly: [],
              neverExpose: [],
            },
          },
        };

        await generateFieldPickingHelpers(tempDir, sensitiveFieldsMap);

        const generatedContent = fs.readFileSync(outputFile, 'utf-8');

        // Test that special characters are properly handled in arrays
        expect(generatedContent).toContain("'field_with_underscores',");
        expect(generatedContent).toContain("'field-with-dashes',");
        expect(generatedContent).toContain("'fieldWithCamelCase'");

        // Test that special characters are properly handled in selectors
        expect(generatedContent).toContain('id: true,');
        expect(generatedContent).toContain("'field-with-dashes': true");
        expect(generatedContent).toContain('fieldWithCamelCase: true');

        // Field with underscores should not be in public selector (it's sensitive)
        const publicSelectorMatch = generatedContent.match(
          /createSpecialModelPublicSelector\(\) \{[^}]+\}/,
        );
        expect(publicSelectorMatch).toBeTruthy();
        expect(publicSelectorMatch[0]).not.toContain('field_with_underscores');

        // But should be in admin selector
        const adminSelectorMatch = generatedContent.match(
          /createSpecialModelAdminSelector\(\) \{[^}]+\}/,
        );
        expect(adminSelectorMatch).toBeTruthy();
        expect(adminSelectorMatch[0]).toContain('field_with_underscores: true');
      });
    });

    describe('Contract: Handle edge cases and validation', () => {
      it('should handle empty sensitive fields map', async () => {
        const emptySensitiveFieldsMap = {};

        await generateFieldPickingHelpers(tempDir, emptySensitiveFieldsMap);

        const generatedContent = fs.readFileSync(outputFile, 'utf-8');

        // Should still generate header and basic structure
        expect(generatedContent).toContain('// Generated by');
        expect(generatedContent).toContain('// DO NOT EDIT - This file is automatically generated');

        // Master exports should be empty
        expect(generatedContent).toContain('export const safeFieldSelectors = {');
        expect(generatedContent).toContain('};');
        expect(generatedContent).toContain('export const adminFieldSelectors = {');
        expect(generatedContent).toContain('};');

        // Should not contain any individual model helpers
        expect(generatedContent).not.toMatch(/\/\/ \w+ field picking helpers/);
      });

      it('should handle model with empty fields', async () => {
        const sensitiveFieldsMap = {
          EmptyModel: {
            allFields: [],
            sensitiveFields: [],
            fieldsWithAnnotations: [],
            fieldsBySecurityLevel: {
              public: [],
              sensitive: [],
              adminOnly: [],
              neverExpose: [],
            },
          },
        };

        await generateFieldPickingHelpers(tempDir, sensitiveFieldsMap);

        const generatedContent = fs.readFileSync(outputFile, 'utf-8');

        // Test empty model helpers
        expect(generatedContent).toContain('// EmptyModel field picking helpers');
        expect(generatedContent).toContain('export const emptymodelSafeFields = [');
        expect(generatedContent).toContain('] as const;');

        // Test empty selectors
        expect(generatedContent).toContain('export function createEmptyModelPublicSelector() {');
        expect(generatedContent).toContain('return {');
        expect(generatedContent).toContain('};');

        expect(generatedContent).toContain('export function createEmptyModelAdminSelector() {');
        expect(generatedContent).toContain('return {');
        expect(generatedContent).toContain('};');

        // Master exports should include empty model
        expect(generatedContent).toContain('emptymodel: createEmptyModelPublicSelector(),');
        expect(generatedContent).toContain('emptymodel: createEmptyModelAdminSelector(),');
      });

      it('should correctly filter sensitive fields from safe fields', async () => {
        const sensitiveFieldsMap = {
          FilterTestModel: {
            allFields: [
              'id',
              'publicField1',
              'sensitiveField1',
              'publicField2',
              'sensitiveField2',
              'publicField3',
            ],
            sensitiveFields: [{ name: 'sensitiveField1' }, { name: 'sensitiveField2' }],
            fieldsWithAnnotations: [
              { name: 'sensitiveField1', securityLevel: 'sensitive' },
              { name: 'sensitiveField2', securityLevel: 'sensitive' },
            ],
            fieldsBySecurityLevel: {
              public: ['id', 'publicField1', 'publicField2', 'publicField3'],
              sensitive: ['sensitiveField1', 'sensitiveField2'],
              adminOnly: [],
              neverExpose: [],
            },
          },
        };

        await generateFieldPickingHelpers(tempDir, sensitiveFieldsMap);

        const generatedContent = fs.readFileSync(outputFile, 'utf-8');

        // Test safe fields exclude sensitive ones
        expect(generatedContent).toContain('export const filtertestmodelSafeFields = [');
        expect(generatedContent).toContain("'id',");
        expect(generatedContent).toContain("'publicField1',");
        expect(generatedContent).toContain("'publicField2',");
        expect(generatedContent).toContain("'publicField3'");

        // Test that safe fields array excludes sensitive fields
        const safeFieldsMatch = generatedContent.match(
          /filtertestmodelSafeFields = \[([\s\S]*?)\] as const;/,
        );
        expect(safeFieldsMatch).toBeTruthy();
        expect(safeFieldsMatch[1]).not.toContain("'sensitiveField1'");
        expect(safeFieldsMatch[1]).not.toContain("'sensitiveField2'");

        // Test all fields include everything
        expect(generatedContent).toContain('export const filtertestmodelAllFields = [');
        expect(generatedContent).toContain("'sensitiveField1',");
        expect(generatedContent).toContain("'sensitiveField2'");

        // Test public selector excludes sensitive fields
        const publicSelectorMatch = generatedContent.match(
          /createFilterTestModelPublicSelector\(\) \{[^}]+\}/,
        );
        expect(publicSelectorMatch).toBeTruthy();
        expect(publicSelectorMatch[0]).toContain('id: true');
        expect(publicSelectorMatch[0]).toContain("'publicField1': true");
        expect(publicSelectorMatch[0]).not.toContain('sensitiveField1');
        expect(publicSelectorMatch[0]).not.toContain('sensitiveField2');

        // Test admin selector includes everything
        const adminSelectorMatch = generatedContent.match(
          /createFilterTestModelAdminSelector\(\) \{[^}]+\}/,
        );
        expect(adminSelectorMatch).toBeTruthy();
        expect(adminSelectorMatch[0]).toContain("'sensitiveField1': true");
        expect(adminSelectorMatch[0]).toContain("'sensitiveField2': true");
      });

      it('should write to correct output directory and filename', async () => {
        const customOutputDir = path.join(process.cwd(), 'custom-field-helpers-output');
        const customOutputFile = path.join(customOutputDir, 'field-selectors.ts');

        try {
          if (!fs.existsSync(customOutputDir)) {
            fs.mkdirSync(customOutputDir, { recursive: true });
          }

          const sensitiveFieldsMap = {
            TestModel: {
              allFields: ['id', 'field1'],
              sensitiveFields: [],
              fieldsWithAnnotations: [],
              fieldsBySecurityLevel: {
                public: ['id', 'field1'],
                sensitive: [],
                adminOnly: [],
                neverExpose: [],
              },
            },
          };

          await generateFieldPickingHelpers(customOutputDir, sensitiveFieldsMap);

          expect(fs.existsSync(customOutputFile)).toBe(true);

          const generatedContent = fs.readFileSync(customOutputFile, 'utf-8');
          expect(generatedContent).toContain('// Generated by');
          expect(generatedContent).toContain('export const testmodelSafeFields');
        } finally {
          // Clean up custom directory
          if (fs.existsSync(customOutputFile)) {
            fs.unlinkSync(customOutputFile);
          }
          if (fs.existsSync(customOutputDir)) {
            fs.rmdirSync(customOutputDir);
          }
        }
      });

      it('should handle model names with complex casing correctly', async () => {
        const sensitiveFieldsMap = {
          ComplexModelName: {
            allFields: ['id', 'data'],
            sensitiveFields: [{ name: 'data' }],
            fieldsWithAnnotations: [{ name: 'data', securityLevel: 'sensitive' }],
            fieldsBySecurityLevel: {
              public: ['id'],
              sensitive: ['data'],
              adminOnly: [],
              neverExpose: [],
            },
          },
          UPPERCASE_MODEL: {
            allFields: ['id', 'value'],
            sensitiveFields: [],
            fieldsWithAnnotations: [],
            fieldsBySecurityLevel: {
              public: ['id', 'value'],
              sensitive: [],
              adminOnly: [],
              neverExpose: [],
            },
          },
          mixedCaseModel: {
            allFields: ['id', 'content'],
            sensitiveFields: [{ name: 'content' }],
            fieldsWithAnnotations: [{ name: 'content', securityLevel: 'sensitive' }],
            fieldsBySecurityLevel: {
              public: ['id'],
              sensitive: ['content'],
              adminOnly: [],
              neverExpose: [],
            },
          },
        };

        await generateFieldPickingHelpers(tempDir, sensitiveFieldsMap);

        const generatedContent = fs.readFileSync(outputFile, 'utf-8');

        // Test lowercase conversion in arrays and functions
        expect(generatedContent).toContain('export const complexmodelnameSafeFields');
        expect(generatedContent).toContain('export const uppercase_modelSafeFields');
        expect(generatedContent).toContain('export const mixedcasemodelSafeFields');

        expect(generatedContent).toContain('export function createComplexModelNamePublicSelector(');
        expect(generatedContent).toContain('export function createUPPERCASE_MODELPublicSelector(');
        expect(generatedContent).toContain('export function createmixedCaseModelPublicSelector(');

        // Test master exports use lowercase for property names
        expect(generatedContent).toContain(
          'complexmodelname: createComplexModelNamePublicSelector(),',
        );
        expect(generatedContent).toContain(
          'uppercase_model: createUPPERCASE_MODELPublicSelector(),',
        );
        expect(generatedContent).toContain('mixedcasemodel: createmixedCaseModelPublicSelector(),');
      });
    });

    describe('Contract: Real-world field picking scenarios', () => {
      it('should generate helpers for comprehensive archival system', async () => {
        const sensitiveFieldsMap = {
          ArchivalDocument: {
            allFields: [
              'id',
              'title',
              'description',
              'dateCreated',
              'personalNames',
              'locationData',
              'adminNotes',
              'processingHistory',
              'originalFileName',
              'fileHash',
              'ocrText',
              'metadata',
            ],
            sensitiveFields: [
              { name: 'personalNames' },
              { name: 'locationData' },
              { name: 'adminNotes' },
              { name: 'fileHash' },
            ],
            fieldsWithAnnotations: [
              { name: 'personalNames', securityLevel: 'sensitive' },
              { name: 'locationData', securityLevel: 'sensitive' },
              { name: 'adminNotes', securityLevel: 'sensitive' },
              { name: 'fileHash', securityLevel: 'sensitive' },
            ],
            fieldsBySecurityLevel: {
              public: [
                'id',
                'title',
                'description',
                'dateCreated',
                'processingHistory',
                'originalFileName',
                'ocrText',
                'metadata',
              ],
              sensitive: ['personalNames', 'locationData', 'adminNotes', 'fileHash'],
              adminOnly: [],
              neverExpose: [],
            },
          },
          User: {
            allFields: ['id', 'username', 'email', 'hashedPassword', 'role', 'organization'],
            sensitiveFields: [{ name: 'email' }, { name: 'hashedPassword' }],
            fieldsWithAnnotations: [
              { name: 'email', securityLevel: 'sensitive' },
              { name: 'hashedPassword', securityLevel: 'never-expose' },
            ],
            fieldsBySecurityLevel: {
              public: ['id', 'username', 'role', 'organization'],
              sensitive: ['email'],
              adminOnly: [],
              neverExpose: ['hashedPassword'],
            },
          },
          ResearchRequest: {
            allFields: ['id', 'purpose', 'requesterId', 'approvedById', 'personalData', 'notes'],
            sensitiveFields: [{ name: 'personalData' }, { name: 'notes' }],
            fieldsWithAnnotations: [
              { name: 'personalData', securityLevel: 'sensitive' },
              { name: 'notes', securityLevel: 'sensitive' },
            ],
            fieldsBySecurityLevel: {
              public: ['id', 'purpose', 'requesterId', 'approvedById'],
              sensitive: ['personalData', 'notes'],
              adminOnly: [],
              neverExpose: [],
            },
          },
        };

        await generateFieldPickingHelpers(tempDir, sensitiveFieldsMap);

        const generatedContent = fs.readFileSync(outputFile, 'utf-8');

        // Test ArchivalDocument helpers
        expect(generatedContent).toContain('// ArchivalDocument field picking helpers');
        expect(generatedContent).toContain('export const archivaldocumentSafeFields = [');
        expect(generatedContent).toContain("'id',");
        expect(generatedContent).toContain("'title',");
        expect(generatedContent).toContain("'description',");
        expect(generatedContent).toContain("'dateCreated',");
        expect(generatedContent).toContain("'originalFileName',");
        expect(generatedContent).toContain("'ocrText',");
        expect(generatedContent).toContain("'metadata'");

        // Should exclude sensitive fields from safe fields
        const archivalSafeFieldsMatch = generatedContent.match(
          /archivaldocumentSafeFields = \[([\s\S]*?)\] as const;/,
        );
        expect(archivalSafeFieldsMatch).toBeTruthy();
        expect(archivalSafeFieldsMatch[1]).not.toContain("'personalNames'");
        expect(archivalSafeFieldsMatch[1]).not.toContain("'locationData'");
        expect(archivalSafeFieldsMatch[1]).not.toContain("'adminNotes'");
        expect(archivalSafeFieldsMatch[1]).not.toContain("'fileHash'");

        // Test public selector excludes sensitive data
        const archivalPublicMatch = generatedContent.match(
          /createArchivalDocumentPublicSelector\(\) \{[^}]+\}/s,
        );
        expect(archivalPublicMatch).toBeTruthy();
        expect(archivalPublicMatch[0]).toContain('title: true');
        expect(archivalPublicMatch[0]).toContain('ocrText: true');
        expect(archivalPublicMatch[0]).not.toContain('personalNames: true');
        expect(archivalPublicMatch[0]).not.toContain('fileHash: true');

        // Test admin selector includes everything
        const archivalAdminMatch = generatedContent.match(
          /createArchivalDocumentAdminSelector\(\) \{[^}]+\}/s,
        );
        expect(archivalAdminMatch).toBeTruthy();
        expect(archivalAdminMatch[0]).toContain('personalNames: true');
        expect(archivalAdminMatch[0]).toContain('locationData: true');
        expect(archivalAdminMatch[0]).toContain('fileHash: true');

        // Test User helpers
        expect(generatedContent).toContain('export const userSafeFields = [');
        expect(generatedContent).toContain("'id',");
        expect(generatedContent).toContain("'username',");
        expect(generatedContent).toContain("'role',");
        expect(generatedContent).toContain("'organization'");

        // Test ResearchRequest helpers
        expect(generatedContent).toContain('export const researchrequestSafeFields = [');
        expect(generatedContent).toContain("'id',");
        expect(generatedContent).toContain("'purpose',");
        expect(generatedContent).toContain("'requesterId',");
        expect(generatedContent).toContain("'approvedById'");

        // Test master exports include all models
        expect(generatedContent).toContain(
          'archivaldocument: createArchivalDocumentPublicSelector(),',
        );
        expect(generatedContent).toContain('user: createUserPublicSelector(),');
        expect(generatedContent).toContain(
          'researchrequest: createResearchRequestPublicSelector(),',
        );
      });

      it('should handle Finnish cultural heritage institution requirements', async () => {
        const sensitiveFieldsMap = {
          CulturalHeritageItem: {
            allFields: [
              'id',
              'catalogNumber',
              'title',
              'description',
              'culturalContext',
              'donorInformation',
              'restrictedCulturalContext',
              'locationOfOrigin',
              'acquisitionNotes',
              'conservationHistory',
              'publicationRestrictions',
            ],
            sensitiveFields: [
              { name: 'donorInformation' },
              { name: 'restrictedCulturalContext' },
              { name: 'locationOfOrigin' },
              { name: 'acquisitionNotes' },
              { name: 'publicationRestrictions' },
            ],
            fieldsWithAnnotations: [
              { name: 'donorInformation', securityLevel: 'sensitive' },
              { name: 'restrictedCulturalContext', securityLevel: 'sensitive' },
              { name: 'locationOfOrigin', securityLevel: 'sensitive' },
              { name: 'acquisitionNotes', securityLevel: 'sensitive' },
              { name: 'publicationRestrictions', securityLevel: 'sensitive' },
            ],
            fieldsBySecurityLevel: {
              public: [
                'id',
                'catalogNumber',
                'title',
                'description',
                'culturalContext',
                'conservationHistory',
              ],
              sensitive: [
                'donorInformation',
                'restrictedCulturalContext',
                'locationOfOrigin',
                'acquisitionNotes',
                'publicationRestrictions',
              ],
              adminOnly: [],
              neverExpose: [],
            },
          },
          Institution: {
            allFields: ['id', 'name', 'type', 'contactInfo', 'internalNotes'],
            sensitiveFields: [{ name: 'contactInfo' }, { name: 'internalNotes' }],
            fieldsWithAnnotations: [
              { name: 'contactInfo', securityLevel: 'sensitive' },
              { name: 'internalNotes', securityLevel: 'sensitive' },
            ],
            fieldsBySecurityLevel: {
              public: ['id', 'name', 'type'],
              sensitive: ['contactInfo', 'internalNotes'],
              adminOnly: [],
              neverExpose: [],
            },
          },
          DigitalPreservationRecord: {
            allFields: [
              'id',
              'originalFormat',
              'preservationFormat',
              'checksum',
              'migrationHistory',
            ],
            sensitiveFields: [{ name: 'checksum' }],
            fieldsWithAnnotations: [{ name: 'checksum', securityLevel: 'sensitive' }],
            fieldsBySecurityLevel: {
              public: ['id', 'originalFormat', 'preservationFormat', 'migrationHistory'],
              sensitive: ['checksum'],
              adminOnly: [],
              neverExpose: [],
            },
          },
        };

        await generateFieldPickingHelpers(tempDir, sensitiveFieldsMap);

        const generatedContent = fs.readFileSync(outputFile, 'utf-8');

        // Test cultural heritage item safe fields
        expect(generatedContent).toContain('export const culturalheritageitemSafeFields = [');
        expect(generatedContent).toContain("'id',");
        expect(generatedContent).toContain("'catalogNumber',");
        expect(generatedContent).toContain("'title',");
        expect(generatedContent).toContain("'description',");
        expect(generatedContent).toContain("'culturalContext',");
        expect(generatedContent).toContain("'conservationHistory'");

        // Sensitive heritage data should be excluded
        const safeFieldsMatch = generatedContent.match(
          /culturalheritageitemSafeFields = \[([\s\S]*?)\] as const;/,
        );
        expect(safeFieldsMatch).toBeTruthy();
        expect(safeFieldsMatch[1]).not.toContain('donorInformation');
        expect(safeFieldsMatch[1]).not.toContain('restrictedCulturalContext');
        expect(safeFieldsMatch[1]).not.toContain('locationOfOrigin');
        expect(safeFieldsMatch[1]).not.toContain('acquisitionNotes');

        // Test public selector for heritage items
        const heritagePublicMatch = generatedContent.match(
          /createCulturalHeritageItemPublicSelector\(\) \{[^}]+\}/s,
        );
        expect(heritagePublicMatch).toBeTruthy();
        expect(heritagePublicMatch[0]).toContain('catalogNumber: true');
        expect(heritagePublicMatch[0]).toContain('culturalContext: true');
        expect(heritagePublicMatch[0]).not.toContain('donorInformation: true');
        expect(heritagePublicMatch[0]).not.toContain('restrictedCulturalContext: true');

        // Test admin selector includes restricted information
        const heritageAdminMatch = generatedContent.match(
          /createCulturalHeritageItemAdminSelector\(\) \{[^}]+\}/s,
        );
        expect(heritageAdminMatch).toBeTruthy();
        expect(heritageAdminMatch[0]).toContain('donorInformation: true');
        expect(heritageAdminMatch[0]).toContain('restrictedCulturalContext: true');
        expect(heritageAdminMatch[0]).toContain('locationOfOrigin: true');

        // Test institution helpers
        expect(generatedContent).toContain('export const institutionSafeFields = [');
        expect(generatedContent).toContain("'id',");
        expect(generatedContent).toContain("'name',");
        expect(generatedContent).toContain("'type'");

        // Test digital preservation record helpers
        expect(generatedContent).toContain('export const digitalpreservationrecordSafeFields = [');
        expect(generatedContent).toContain("'originalFormat',");
        expect(generatedContent).toContain("'preservationFormat',");
        expect(generatedContent).toContain("'migrationHistory'");

        // Master exports should include all heritage models
        expect(generatedContent).toContain(
          'culturalheritageitem: createCulturalHeritageItemPublicSelector(),',
        );
        expect(generatedContent).toContain('institution: createInstitutionPublicSelector(),');
        expect(generatedContent).toContain(
          'digitalpreservationrecord: createDigitalPreservationRecordPublicSelector(),',
        );
      });

      it('should handle complex mixed security scenarios', async () => {
        const sensitiveFieldsMap = {
          SecurityTestModel: {
            allFields: [
              'publicField1',
              'publicField2',
              'publicField3',
              'sensitiveField1',
              'sensitiveField2',
              'sensitiveField3',
              'sensitiveField4',
              'specialCharField_1',
              'special-char-field-2',
              'fieldWithCamelCase',
            ],
            sensitiveFields: [
              { name: 'sensitiveField1' },
              { name: 'sensitiveField2' },
              { name: 'sensitiveField3' },
              { name: 'sensitiveField4' },
              { name: 'specialCharField_1' },
            ],
            fieldsWithAnnotations: [
              { name: 'sensitiveField1', securityLevel: 'sensitive' },
              { name: 'sensitiveField2', securityLevel: 'sensitive' },
              { name: 'sensitiveField3', securityLevel: 'sensitive' },
              { name: 'sensitiveField4', securityLevel: 'sensitive' },
              { name: 'specialCharField_1', securityLevel: 'sensitive' },
            ],
            fieldsBySecurityLevel: {
              public: [
                'publicField1',
                'publicField2',
                'publicField3',
                'special-char-field-2',
                'fieldWithCamelCase',
              ],
              sensitive: [
                'sensitiveField1',
                'sensitiveField2',
                'sensitiveField3',
                'sensitiveField4',
                'specialCharField_1',
              ],
              'never-expose': [],
              'admin-only': [],
            },
          },
        };

        await generateFieldPickingHelpers(tempDir, sensitiveFieldsMap);

        const generatedContent = fs.readFileSync(outputFile, 'utf-8');

        // Test safe fields exclude all sensitive ones
        expect(generatedContent).toContain('export const securitytestmodelSafeFields = [');
        expect(generatedContent).toContain("'publicField1',");
        expect(generatedContent).toContain("'publicField2',");
        expect(generatedContent).toContain("'publicField3',");
        expect(generatedContent).toContain("'special-char-field-2',");
        expect(generatedContent).toContain("'fieldWithCamelCase'");

        // Verify sensitive fields are excluded from safe fields
        const safeFieldsSection = generatedContent.match(
          /securitytestmodelSafeFields = \[([\s\S]*?)\] as const;/,
        );
        expect(safeFieldsSection).toBeTruthy();
        expect(safeFieldsSection[1]).not.toContain('sensitiveField1');
        expect(safeFieldsSection[1]).not.toContain('sensitiveField2');
        expect(safeFieldsSection[1]).not.toContain('sensitiveField3');
        expect(safeFieldsSection[1]).not.toContain('sensitiveField4');
        expect(safeFieldsSection[1]).not.toContain('specialCharField_1');

        // Test all fields include everything
        expect(generatedContent).toContain('export const securitytestmodelAllFields = [');
        const allFieldsSection = generatedContent.match(
          /securitytestmodelAllFields = \[([\s\S]*?)\] as const;/,
        );
        expect(allFieldsSection).toBeTruthy();
        expect(allFieldsSection[1]).toContain('sensitiveField1');
        expect(allFieldsSection[1]).toContain('sensitiveField4');
        expect(allFieldsSection[1]).toContain('specialCharField_1');

        // Test public selector handles special characters
        const publicSelectorMatch = generatedContent.match(
          /createSecurityTestModelPublicSelector\(\) \{[^}]+\}/s,
        );
        expect(publicSelectorMatch).toBeTruthy();
        expect(publicSelectorMatch[0]).toContain("'publicField1': true");
        expect(publicSelectorMatch[0]).toContain("'special-char-field-2': true");
        expect(publicSelectorMatch[0]).toContain('fieldWithCamelCase: true');
        expect(publicSelectorMatch[0]).not.toContain('sensitiveField');
        expect(publicSelectorMatch[0]).not.toContain('specialCharField_1');

        // Test admin selector includes everything with proper formatting
        const adminSelectorMatch = generatedContent.match(
          /createSecurityTestModelAdminSelector\(\) \{[^}]+\}/s,
        );
        expect(adminSelectorMatch).toBeTruthy();
        expect(adminSelectorMatch[0]).toContain("'sensitiveField1': true");
        expect(adminSelectorMatch[0]).toContain("'sensitiveField4': true");
        expect(adminSelectorMatch[0]).toContain("'specialCharField_1': true");
        expect(adminSelectorMatch[0]).toContain("'special-char-field-2': true");
      });
    });
  });
});
